server:
  port: 80

spring:
  ai:
    chat:
      client:
        observations:
          include-prompt: true
    mcp:
      client:
        sse:
          transport-mode: WEBFLUX
          connections:
            stock-mcp-server:
              url: http://localhost:8080
            person-mcp-server:
              url: http://localhost:8060
            account-mcp-server:
              url: http://localhost:8040
            notification-mcp-server:
              url: http://localhost:8020
    ollama:
      chat:
        options:
# see https://ollama.com/dwightfoster03/functionary-small-v3.1
          model: smollm2
      base-url: https://e488-34-67-71-235.ngrok-free.app

logging:
  level:
    root: INFO
    com.agilesolutions.chatbot: DEBUG
    org.springframework.ai: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true